//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piano1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("piano1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ___1 {
            get {
                object obj = ResourceManager.GetObject("___1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ___2 {
            get {
                object obj = ResourceManager.GetObject("___2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ___3 {
            get {
                object obj = ResourceManager.GetObject("___3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ___4 {
            get {
                object obj = ResourceManager.GetObject("___4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ___5 {
            get {
                object obj = ResourceManager.GetObject("___5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap @__1 {
            get {
                object obj = ResourceManager.GetObject("__1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap @__2 {
            get {
                object obj = ResourceManager.GetObject("__2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap @__3 {
            get {
                object obj = ResourceManager.GetObject("__3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap @__4 {
            get {
                object obj = ResourceManager.GetObject("__4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap @__5 {
            get {
                object obj = ResourceManager.GetObject("__5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap @__6 {
            get {
                object obj = ResourceManager.GetObject("__6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap @__7 {
            get {
                object obj = ResourceManager.GetObject("__7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _1 {
            get {
                return ResourceManager.GetStream("_1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _1_ {
            get {
                object obj = ResourceManager.GetObject("_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1__ {
            get {
                object obj = ResourceManager.GetObject("_1__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1___ {
            get {
                object obj = ResourceManager.GetObject("_1___", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _10 {
            get {
                return ResourceManager.GetStream("_10", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _11 {
            get {
                return ResourceManager.GetStream("_11", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _110 {
            get {
                object obj = ResourceManager.GetObject("_110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _111 {
            get {
                object obj = ResourceManager.GetObject("_111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _12 {
            get {
                return ResourceManager.GetStream("_12", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _13 {
            get {
                return ResourceManager.GetStream("_13", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _14 {
            get {
                return ResourceManager.GetStream("_14", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _15 {
            get {
                return ResourceManager.GetStream("_15", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _16 {
            get {
                return ResourceManager.GetStream("_16", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _17 {
            get {
                return ResourceManager.GetStream("_17", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _18 {
            get {
                return ResourceManager.GetStream("_18", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _19 {
            get {
                return ResourceManager.GetStream("_19", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _2 {
            get {
                return ResourceManager.GetStream("_2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _2_ {
            get {
                object obj = ResourceManager.GetObject("_2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2__ {
            get {
                object obj = ResourceManager.GetObject("_2__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2___ {
            get {
                object obj = ResourceManager.GetObject("_2___", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _20 {
            get {
                return ResourceManager.GetStream("_20", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _21 {
            get {
                return ResourceManager.GetStream("_21", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _210 {
            get {
                object obj = ResourceManager.GetObject("_210", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _211 {
            get {
                object obj = ResourceManager.GetObject("_211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _22 {
            get {
                return ResourceManager.GetStream("_22", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _23 {
            get {
                return ResourceManager.GetStream("_23", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _24 {
            get {
                return ResourceManager.GetStream("_24", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _25 {
            get {
                return ResourceManager.GetStream("_25", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _26 {
            get {
                return ResourceManager.GetStream("_26", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _27 {
            get {
                return ResourceManager.GetStream("_27", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _28 {
            get {
                return ResourceManager.GetStream("_28", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _29 {
            get {
                return ResourceManager.GetStream("_29", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _3 {
            get {
                return ResourceManager.GetStream("_3", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _3_ {
            get {
                object obj = ResourceManager.GetObject("_3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3__ {
            get {
                object obj = ResourceManager.GetObject("_3__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3___ {
            get {
                object obj = ResourceManager.GetObject("_3___", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _30 {
            get {
                return ResourceManager.GetStream("_30", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _31 {
            get {
                return ResourceManager.GetStream("_31", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _310 {
            get {
                object obj = ResourceManager.GetObject("_310", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _311 {
            get {
                object obj = ResourceManager.GetObject("_311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _32 {
            get {
                return ResourceManager.GetStream("_32", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _33 {
            get {
                return ResourceManager.GetStream("_33", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _34 {
            get {
                return ResourceManager.GetStream("_34", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _35 {
            get {
                return ResourceManager.GetStream("_35", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _36 {
            get {
                return ResourceManager.GetStream("_36", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _37 {
            get {
                return ResourceManager.GetStream("_37", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _38 {
            get {
                return ResourceManager.GetStream("_38", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _39 {
            get {
                return ResourceManager.GetStream("_39", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _4 {
            get {
                return ResourceManager.GetStream("_4", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _4_ {
            get {
                object obj = ResourceManager.GetObject("_4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4__ {
            get {
                object obj = ResourceManager.GetObject("_4__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4___ {
            get {
                object obj = ResourceManager.GetObject("_4___", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _40 {
            get {
                return ResourceManager.GetStream("_40", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _41 {
            get {
                return ResourceManager.GetStream("_41", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _410 {
            get {
                object obj = ResourceManager.GetObject("_410", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _411 {
            get {
                object obj = ResourceManager.GetObject("_411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _42 {
            get {
                return ResourceManager.GetStream("_42", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _43 {
            get {
                return ResourceManager.GetStream("_43", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _44 {
            get {
                return ResourceManager.GetStream("_44", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _45 {
            get {
                return ResourceManager.GetStream("_45", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _46 {
            get {
                return ResourceManager.GetStream("_46", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _47 {
            get {
                return ResourceManager.GetStream("_47", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _48 {
            get {
                return ResourceManager.GetStream("_48", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _49 {
            get {
                return ResourceManager.GetStream("_49", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _5 {
            get {
                return ResourceManager.GetStream("_5", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _5_ {
            get {
                object obj = ResourceManager.GetObject("_5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5__ {
            get {
                object obj = ResourceManager.GetObject("_5__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5___ {
            get {
                object obj = ResourceManager.GetObject("_5___", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _50 {
            get {
                return ResourceManager.GetStream("_50", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _51 {
            get {
                return ResourceManager.GetStream("_51", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _510 {
            get {
                object obj = ResourceManager.GetObject("_510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _511 {
            get {
                object obj = ResourceManager.GetObject("_511", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _52 {
            get {
                return ResourceManager.GetStream("_52", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _53 {
            get {
                return ResourceManager.GetStream("_53", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _54 {
            get {
                return ResourceManager.GetStream("_54", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _55 {
            get {
                return ResourceManager.GetStream("_55", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _56 {
            get {
                return ResourceManager.GetStream("_56", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _57 {
            get {
                return ResourceManager.GetStream("_57", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _58 {
            get {
                return ResourceManager.GetStream("_58", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _59 {
            get {
                return ResourceManager.GetStream("_59", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _6 {
            get {
                return ResourceManager.GetStream("_6", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _6_ {
            get {
                object obj = ResourceManager.GetObject("_6_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6__ {
            get {
                object obj = ResourceManager.GetObject("_6__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6___ {
            get {
                object obj = ResourceManager.GetObject("_6___", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _60 {
            get {
                return ResourceManager.GetStream("_60", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _61 {
            get {
                return ResourceManager.GetStream("_61", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _610 {
            get {
                object obj = ResourceManager.GetObject("_610", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _611 {
            get {
                object obj = ResourceManager.GetObject("_611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _62 {
            get {
                return ResourceManager.GetStream("_62", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _63 {
            get {
                return ResourceManager.GetStream("_63", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _64 {
            get {
                return ResourceManager.GetStream("_64", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _65 {
            get {
                return ResourceManager.GetStream("_65", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _66 {
            get {
                return ResourceManager.GetStream("_66", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _67 {
            get {
                return ResourceManager.GetStream("_67", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _68 {
            get {
                return ResourceManager.GetStream("_68", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _69 {
            get {
                return ResourceManager.GetStream("_69", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _7 {
            get {
                return ResourceManager.GetStream("_7", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _7_ {
            get {
                object obj = ResourceManager.GetObject("_7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7__ {
            get {
                object obj = ResourceManager.GetObject("_7__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7___ {
            get {
                object obj = ResourceManager.GetObject("_7___", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _70 {
            get {
                return ResourceManager.GetStream("_70", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _71 {
            get {
                return ResourceManager.GetStream("_71", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _710 {
            get {
                object obj = ResourceManager.GetObject("_710", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _711 {
            get {
                object obj = ResourceManager.GetObject("_711", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _72 {
            get {
                return ResourceManager.GetStream("_72", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _73 {
            get {
                return ResourceManager.GetStream("_73", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _74 {
            get {
                return ResourceManager.GetStream("_74", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _75 {
            get {
                return ResourceManager.GetStream("_75", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _76 {
            get {
                return ResourceManager.GetStream("_76", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _77 {
            get {
                return ResourceManager.GetStream("_77", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _7763555_115539225170_2_副本 {
            get {
                object obj = ResourceManager.GetObject("_7763555_115539225170_2_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _78 {
            get {
                return ResourceManager.GetStream("_78", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _79 {
            get {
                return ResourceManager.GetStream("_79", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _8 {
            get {
                return ResourceManager.GetStream("_8", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _80 {
            get {
                return ResourceManager.GetStream("_80", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _81 {
            get {
                return ResourceManager.GetStream("_81", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _82 {
            get {
                return ResourceManager.GetStream("_82", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _83 {
            get {
                return ResourceManager.GetStream("_83", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _84 {
            get {
                return ResourceManager.GetStream("_84", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _85 {
            get {
                return ResourceManager.GetStream("_85", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _86 {
            get {
                return ResourceManager.GetStream("_86", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _8671977_002743575172_2 {
            get {
                object obj = ResourceManager.GetObject("8671977_002743575172_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _87 {
            get {
                return ResourceManager.GetStream("_87", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _88 {
            get {
                return ResourceManager.GetStream("_88", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _9 {
            get {
                return ResourceManager.GetStream("_9", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GQ {
            get {
                object obj = ResourceManager.GetObject("GQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap piano {
            get {
                object obj = ResourceManager.GetObject("piano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap piano2 {
            get {
                object obj = ResourceManager.GetObject("piano2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s1 {
            get {
                object obj = ResourceManager.GetObject("s1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s2 {
            get {
                object obj = ResourceManager.GetObject("s2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t0148310c89ae5a8f93 {
            get {
                object obj = ResourceManager.GetObject("t0148310c89ae5a8f93", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yinf {
            get {
                object obj = ResourceManager.GetObject("yinf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 未命名 {
            get {
                object obj = ResourceManager.GetObject("未命名", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 未命名_副本 {
            get {
                object obj = ResourceManager.GetObject("未命名_副本", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 未命名1 {
            get {
                object obj = ResourceManager.GetObject("未命名1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 电脑键盘窗口 {
            get {
                object obj = ResourceManager.GetObject("电脑键盘窗口", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 电脑键盘窗口2 {
            get {
                object obj = ResourceManager.GetObject("电脑键盘窗口2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
